# Generated by Django 5.2.3 on 2025-12-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteBoardAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=20)),
                ('element_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiteboard_app.whiteboard')),
            ],
        ),
    ]
