# Generated by Django 5.2.3 on 2025-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard_app', '0002_whiteboardaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiteboardaction',
            name='action_type',
            field=models.CharField(choices=[('add', 'Add'), ('delete', 'Delete')], max_length=20),
        ),
    ]
